# Python CircleCI 2.0 configuration file
#
# https://circleci.com/docs/2.0/language-python/
version: 2
jobs:
  build:
    docker:
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:2.7.13

    working_directory: ~/pymoji
    steps:
      - checkout

      # Install and configure Google Cloud
      # https://circleci.com/docs/2.0/google-container-engine/
      - run:
          name: decode gcloud credentials
          command: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - restore_cache:
          keys:
          - google-cloud-sdk-{{ checksum "gcloud.version" }}
          # fallback to using the latest cache if no exact match is found
          - google-cloud-sdk-
      - run:
          name: install gcloud sdk
          command: |
            if [ ! -d ${HOME}/google-cloud-sdk ]; then
              curl https://sdk.cloud.google.com | bash
            fi
          environment:
            CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      - run:
          name: update gcloud sdk
          command: |
            ${HOME}/google-cloud-sdk/bin/gcloud --quiet components update
            ${HOME}/google-cloud-sdk/bin/gcloud --version > gcloud.version
      - save_cache:
          paths:
            - ${HOME}/google-cloud-sdk
          key: google-cloud-sdk-{{ checksum "gcloud.version" }}

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install python dependencies
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # Run tests and save results
      - run:
          name: run tests
          command: |
            source venv/bin/activate
            python -m pytest --junitxml=tmp/test-reports.xml
      - store_test_results:
          path: tmp
      - store_artifacts:
          path: tmp

      # Deploy successful builds on master to Google App Engine
      # https://circleci.com/docs/2.0/deployment_integrations/
      - deploy:
          name: maybe deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ${HOME}/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
              ${HOME}/google-cloud-sdk/bin/gcloud --quiet config set project $GCLOUD_PROJECT_ID
              ${HOME}/google-cloud-sdk/bin/gcloud --quiet app deploy --promote
            fi

